"""Criaçao de ProductDiscount

Revision ID: 287f1ec13948
Revises: 08c0a337fbc3
Create Date: 2021-12-13 13:33:18.228600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287f1ec13948'
down_revision = '08c0a337fbc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=45), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_method_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_discount')
    # ### end Alembic commands ###
