"""criando o campo created_at em product

Revision ID: 96190e639cbd
Revises: 07310f174966
Create Date: 2021-12-03 11:10:22.343099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96190e639cbd'
down_revision = '07310f174966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###
